### ISSUE TITLE
Snyk step failing with "command not found"

### ISSUE THREAD

**Issue by tiborarthofer** [pilvikala/bitrise-step-snyk#4]
Hi Michal,

I am working for Bitrise support and we noticed that since last week, the Test with Snyk step started to fail with the following error message:

Exit status -127

+ set -o pipefail
+ command_to_use=test
+ [[ -z test ]]
+ [[ test = \t\e\s\t\_\t\h\i\s\_\s\t\e\p ]]
+ packages=snyk
+ [[ no == \y\e\s ]]
+ npm install --location=global snyk
added 36 packages, and audited 37 packages in 8s
8 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
+ target_file_arg=
+ org_arg=
+ snyk auth [REDACTED]
/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/bitrise2944629925/step_src/step.sh: line 39: snyk: command not found

This workflow was not modified in any way and we were unable to find any issues with the app setup, could you take a look?

Thanks in advance!

**Comment by pilvikala** [comment]
Looking

**Comment by pilvikala** [comment]
I have opened a PR. Can you run the test using the step from the branch and see if it succeeds? To do this, change the step name in the yml from `snyk@1` to:

```
git::https://github.com/pilvikala/bitrise-step-snyk.git@1-fix-npm-install
```
